#!/bin/bash

qsub -cwd -j y -l mem_free=10G,act_mem_free=10G,h_vmem=12G -M droganova@ufal.mff.cuni.cz -m beas tr_imst-ud-test.conllu.sh
qsub -cwd -j y -l mem_free=10G,act_mem_free=10G,h_vmem=12G -M droganova@ufal.mff.cuni.cz -m beas tr_imst-ud-train.conllu.sh
qsub -cwd -j y -l mem_free=10G,act_mem_free=10G,h_vmem=12G -M droganova@ufal.mff.cuni.cz -m beas tr_imst-ud-dev.conllu.sh
qsub -cwd -j y -l mem_free=10G,act_mem_free=10G,h_vmem=12G -M droganova@ufal.mff.cuni.cz -m beas nl_lassysmall-ud-test.conllu.sh
qsub -cwd -j y -l mem_free=10G,act_mem_free=10G,h_vmem=12G -M droganova@ufal.mff.cuni.cz -m beas nl_lassysmall-ud-train.conllu.sh
qsub -cwd -j y -l mem_free=10G,act_mem_free=10G,h_vmem=12G -M droganova@ufal.mff.cuni.cz -m beas nl_lassysmall-ud-dev.conllu.sh
qsub -cwd -j y -l mem_free=10G,act_mem_free=10G,h_vmem=12G -M droganova@ufal.mff.cuni.cz -m beas uk_iu-ud-train.conllu.sh
qsub -cwd -j y -l mem_free=10G,act_mem_free=10G,h_vmem=12G -M droganova@ufal.mff.cuni.cz -m beas uk_iu-ud-test.conllu.sh
qsub -cwd -j y -l mem_free=10G,act_mem_free=10G,h_vmem=12G -M droganova@ufal.mff.cuni.cz -m beas uk_iu-ud-dev.conllu.sh
qsub -cwd -j y -l mem_free=10G,act_mem_free=10G,h_vmem=12G -M droganova@ufal.mff.cuni.cz -m beas es_ancora-ud-train.conllu.sh
qsub -cwd -j y -l mem_free=10G,act_mem_free=10G,h_vmem=12G -M droganova@ufal.mff.cuni.cz -m beas es_ancora-ud-test.conllu.sh
qsub -cwd -j y -l mem_free=10G,act_mem_free=10G,h_vmem=12G -M droganova@ufal.mff.cuni.cz -m beas es_ancora-ud-dev.conllu.sh
qsub -cwd -j y -l mem_free=10G,act_mem_free=10G,h_vmem=12G -M droganova@ufal.mff.cuni.cz -m beas cu_proiel-ud-train.conllu.sh
qsub -cwd -j y -l mem_free=10G,act_mem_free=10G,h_vmem=12G -M droganova@ufal.mff.cuni.cz -m beas cu_proiel-ud-dev.conllu.sh
qsub -cwd -j y -l mem_free=10G,act_mem_free=10G,h_vmem=12G -M droganova@ufal.mff.cuni.cz -m beas cu_proiel-ud-test.conllu.sh
qsub -cwd -j y -l mem_free=10G,act_mem_free=10G,h_vmem=12G -M droganova@ufal.mff.cuni.cz -m beas cs_cac-ud-test.conllu.sh
qsub -cwd -j y -l mem_free=10G,act_mem_free=10G,h_vmem=12G -M droganova@ufal.mff.cuni.cz -m beas cs_cac-ud-dev.conllu.sh
qsub -cwd -j y -l mem_free=10G,act_mem_free=10G,h_vmem=12G -M droganova@ufal.mff.cuni.cz -m beas cs_cac-ud-train.conllu.sh
qsub -cwd -j y -l mem_free=10G,act_mem_free=10G,h_vmem=12G -M droganova@ufal.mff.cuni.cz -m beas it_isdt-ud-dev.conllu.sh
qsub -cwd -j y -l mem_free=10G,act_mem_free=10G,h_vmem=12G -M droganova@ufal.mff.cuni.cz -m beas it_isdt-ud-test.conllu.sh
qsub -cwd -j y -l mem_free=10G,act_mem_free=10G,h_vmem=12G -M droganova@ufal.mff.cuni.cz -m beas it_isdt-ud-train.conllu.sh
qsub -cwd -j y -l mem_free=10G,act_mem_free=10G,h_vmem=12G -M droganova@ufal.mff.cuni.cz -m beas it_partut-ud-dev.conllu.sh
qsub -cwd -j y -l mem_free=10G,act_mem_free=10G,h_vmem=12G -M droganova@ufal.mff.cuni.cz -m beas it_partut-ud-test.conllu.sh
qsub -cwd -j y -l mem_free=10G,act_mem_free=10G,h_vmem=12G -M droganova@ufal.mff.cuni.cz -m beas it_partut-ud-train.conllu.sh
qsub -cwd -j y -l mem_free=10G,act_mem_free=10G,h_vmem=12G -M droganova@ufal.mff.cuni.cz -m beas hy_armtdp-ud-train.conllu.sh
qsub -cwd -j y -l mem_free=10G,act_mem_free=10G,h_vmem=12G -M droganova@ufal.mff.cuni.cz -m beas hy_armtdp-ud-dev.conllu.sh
qsub -cwd -j y -l mem_free=10G,act_mem_free=10G,h_vmem=12G -M droganova@ufal.mff.cuni.cz -m beas hy_armtdp-ud-test.conllu.sh
qsub -cwd -j y -l mem_free=10G,act_mem_free=10G,h_vmem=12G -M droganova@ufal.mff.cuni.cz -m beas de_lit-ud-test.conllu.sh
qsub -cwd -j y -l mem_free=10G,act_mem_free=10G,h_vmem=12G -M droganova@ufal.mff.cuni.cz -m beas en_pud-ud-test.conllu.sh
qsub -cwd -j y -l mem_free=10G,act_mem_free=10G,h_vmem=12G -M droganova@ufal.mff.cuni.cz -m beas ja_pud-ud-test.conllu.sh
qsub -cwd -j y -l mem_free=10G,act_mem_free=10G,h_vmem=12G -M droganova@ufal.mff.cuni.cz -m beas ja_gsd-ud-dev.conllu.sh
qsub -cwd -j y -l mem_free=10G,act_mem_free=10G,h_vmem=12G -M droganova@ufal.mff.cuni.cz -m beas ja_gsd-ud-test.conllu.sh
qsub -cwd -j y -l mem_free=10G,act_mem_free=10G,h_vmem=12G -M droganova@ufal.mff.cuni.cz -m beas ja_gsd-ud-train.conllu.sh
qsub -cwd -j y -l mem_free=10G,act_mem_free=10G,h_vmem=12G -M droganova@ufal.mff.cuni.cz -m beas ca_ancora-ud-dev.conllu.sh
qsub -cwd -j y -l mem_free=10G,act_mem_free=10G,h_vmem=12G -M droganova@ufal.mff.cuni.cz -m beas ca_ancora-ud-test.conllu.sh
qsub -cwd -j y -l mem_free=10G,act_mem_free=10G,h_vmem=12G -M droganova@ufal.mff.cuni.cz -m beas ca_ancora-ud-train.conllu.sh
qsub -cwd -j y -l mem_free=10G,act_mem_free=10G,h_vmem=12G -M droganova@ufal.mff.cuni.cz -m beas sk_snk-ud-dev.conllu.sh
qsub -cwd -j y -l mem_free=10G,act_mem_free=10G,h_vmem=12G -M droganova@ufal.mff.cuni.cz -m beas sk_snk-ud-train.conllu.sh
qsub -cwd -j y -l mem_free=10G,act_mem_free=10G,h_vmem=12G -M droganova@ufal.mff.cuni.cz -m beas sk_snk-ud-test.conllu.sh
qsub -cwd -j y -l mem_free=10G,act_mem_free=10G,h_vmem=12G -M droganova@ufal.mff.cuni.cz -m beas bg_btb-ud-dev.conllu.sh
qsub -cwd -j y -l mem_free=10G,act_mem_free=10G,h_vmem=12G -M droganova@ufal.mff.cuni.cz -m beas bg_btb-ud-train.conllu.sh
qsub -cwd -j y -l mem_free=10G,act_mem_free=10G,h_vmem=12G -M droganova@ufal.mff.cuni.cz -m beas bg_btb-ud-test.conllu.sh
qsub -cwd -j y -l mem_free=10G,act_mem_free=10G,h_vmem=12G -M droganova@ufal.mff.cuni.cz -m beas got_proiel-ud-dev.conllu.sh
qsub -cwd -j y -l mem_free=10G,act_mem_free=10G,h_vmem=12G -M droganova@ufal.mff.cuni.cz -m beas got_proiel-ud-test.conllu.sh
qsub -cwd -j y -l mem_free=10G,act_mem_free=10G,h_vmem=12G -M droganova@ufal.mff.cuni.cz -m beas got_proiel-ud-train.conllu.sh
qsub -cwd -j y -l mem_free=10G,act_mem_free=10G,h_vmem=12G -M droganova@ufal.mff.cuni.cz -m beas aii_as-ud-test.conllu.sh
qsub -cwd -j y -l mem_free=10G,act_mem_free=10G,h_vmem=12G -M droganova@ufal.mff.cuni.cz -m beas af_afribooms-ud-train.conllu.sh
qsub -cwd -j y -l mem_free=10G,act_mem_free=10G,h_vmem=12G -M droganova@ufal.mff.cuni.cz -m beas af_afribooms-ud-dev.conllu.sh
qsub -cwd -j y -l mem_free=10G,act_mem_free=10G,h_vmem=12G -M droganova@ufal.mff.cuni.cz -m beas af_afribooms-ud-test.conllu.sh
qsub -cwd -j y -l mem_free=10G,act_mem_free=10G,h_vmem=12G -M droganova@ufal.mff.cuni.cz -m beas sr_set-ud-dev.conllu.sh
qsub -cwd -j y -l mem_free=10G,act_mem_free=10G,h_vmem=12G -M droganova@ufal.mff.cuni.cz -m beas sr_set-ud-test.conllu.sh
qsub -cwd -j y -l mem_free=10G,act_mem_free=10G,h_vmem=12G -M droganova@ufal.mff.cuni.cz -m beas sr_set-ud-train.conllu.sh
qsub -cwd -j y -l mem_free=10G,act_mem_free=10G,h_vmem=12G -M droganova@ufal.mff.cuni.cz -m beas kk_ktb-ud-test.conllu.sh
qsub -cwd -j y -l mem_free=10G,act_mem_free=10G,h_vmem=12G -M droganova@ufal.mff.cuni.cz -m beas kk_ktb-ud-train.conllu.sh
qsub -cwd -j y -l mem_free=10G,act_mem_free=10G,h_vmem=12G -M droganova@ufal.mff.cuni.cz -m beas tr_gb-ud-test.conllu.sh
qsub -cwd -j y -l mem_free=10G,act_mem_free=10G,h_vmem=12G -M droganova@ufal.mff.cuni.cz -m beas ug_udt-ud-dev.conllu.sh
qsub -cwd -j y -l mem_free=10G,act_mem_free=10G,h_vmem=12G -M droganova@ufal.mff.cuni.cz -m beas ug_udt-ud-train.conllu.sh
qsub -cwd -j y -l mem_free=10G,act_mem_free=10G,h_vmem=12G -M droganova@ufal.mff.cuni.cz -m beas ug_udt-ud-test.conllu.sh
qsub -cwd -j y -l mem_free=10G,act_mem_free=10G,h_vmem=12G -M droganova@ufal.mff.cuni.cz -m beas en_gum-ud-train.conllu.sh
qsub -cwd -j y -l mem_free=10G,act_mem_free=10G,h_vmem=12G -M droganova@ufal.mff.cuni.cz -m beas en_gum-ud-test.conllu.sh
qsub -cwd -j y -l mem_free=10G,act_mem_free=10G,h_vmem=12G -M droganova@ufal.mff.cuni.cz -m beas en_gum-ud-dev.conllu.sh
qsub -cwd -j y -l mem_free=10G,act_mem_free=10G,h_vmem=12G -M droganova@ufal.mff.cuni.cz -m beas kpv_ikdp-ud-test.conllu.sh
qsub -cwd -j y -l mem_free=10G,act_mem_free=10G,h_vmem=12G -M droganova@ufal.mff.cuni.cz -m beas hu_szeged-ud-test.conllu.sh
qsub -cwd -j y -l mem_free=10G,act_mem_free=10G,h_vmem=12G -M droganova@ufal.mff.cuni.cz -m beas hu_szeged-ud-dev.conllu.sh
qsub -cwd -j y -l mem_free=10G,act_mem_free=10G,h_vmem=12G -M droganova@ufal.mff.cuni.cz -m beas hu_szeged-ud-train.conllu.sh
qsub -cwd -j y -l mem_free=10G,act_mem_free=10G,h_vmem=12G -M droganova@ufal.mff.cuni.cz -m beas orv_torot-ud-dev.conllu.sh
qsub -cwd -j y -l mem_free=10G,act_mem_free=10G,h_vmem=12G -M droganova@ufal.mff.cuni.cz -m beas orv_torot-ud-train.conllu.sh
qsub -cwd -j y -l mem_free=10G,act_mem_free=10G,h_vmem=12G -M droganova@ufal.mff.cuni.cz -m beas orv_torot-ud-test.conllu.sh
qsub -cwd -j y -l mem_free=10G,act_mem_free=10G,h_vmem=12G -M droganova@ufal.mff.cuni.cz -m beas et_edt-ud-test.conllu.sh
qsub -cwd -j y -l mem_free=10G,act_mem_free=10G,h_vmem=12G -M droganova@ufal.mff.cuni.cz -m beas et_edt-ud-dev.conllu.sh
qsub -cwd -j y -l mem_free=10G,act_mem_free=10G,h_vmem=12G -M droganova@ufal.mff.cuni.cz -m beas et_edt-ud-train.conllu.sh
qsub -cwd -j y -l mem_free=10G,act_mem_free=10G,h_vmem=12G -M droganova@ufal.mff.cuni.cz -m beas da_ddt-ud-test.conllu.sh
qsub -cwd -j y -l mem_free=10G,act_mem_free=10G,h_vmem=12G -M droganova@ufal.mff.cuni.cz -m beas da_ddt-ud-dev.conllu.sh
qsub -cwd -j y -l mem_free=10G,act_mem_free=10G,h_vmem=12G -M droganova@ufal.mff.cuni.cz -m beas da_ddt-ud-train.conllu.sh
qsub -cwd -j y -l mem_free=10G,act_mem_free=10G,h_vmem=12G -M droganova@ufal.mff.cuni.cz -m beas hsb_ufal-ud-test.conllu.sh
qsub -cwd -j y -l mem_free=10G,act_mem_free=10G,h_vmem=12G -M droganova@ufal.mff.cuni.cz -m beas hsb_ufal-ud-train.conllu.sh
qsub -cwd -j y -l mem_free=10G,act_mem_free=10G,h_vmem=12G -M droganova@ufal.mff.cuni.cz -m beas eu_bdt-ud-dev.conllu.sh
qsub -cwd -j y -l mem_free=10G,act_mem_free=10G,h_vmem=12G -M droganova@ufal.mff.cuni.cz -m beas eu_bdt-ud-test.conllu.sh
qsub -cwd -j y -l mem_free=10G,act_mem_free=10G,h_vmem=12G -M droganova@ufal.mff.cuni.cz -m beas eu_bdt-ud-train.conllu.sh
qsub -cwd -j y -l mem_free=10G,act_mem_free=10G,h_vmem=12G -M droganova@ufal.mff.cuni.cz -m beas pt_bosque-ud-dev.conllu.sh
qsub -cwd -j y -l mem_free=10G,act_mem_free=10G,h_vmem=12G -M droganova@ufal.mff.cuni.cz -m beas pt_bosque-ud-test.conllu.sh
qsub -cwd -j y -l mem_free=10G,act_mem_free=10G,h_vmem=12G -M droganova@ufal.mff.cuni.cz -m beas pt_bosque-ud-train.conllu.sh
qsub -cwd -j y -l mem_free=10G,act_mem_free=10G,h_vmem=12G -M droganova@ufal.mff.cuni.cz -m beas ru_taiga-ud-train.conllu.sh
qsub -cwd -j y -l mem_free=10G,act_mem_free=10G,h_vmem=12G -M droganova@ufal.mff.cuni.cz -m beas ru_taiga-ud-test.conllu.sh
qsub -cwd -j y -l mem_free=10G,act_mem_free=10G,h_vmem=12G -M droganova@ufal.mff.cuni.cz -m beas ru_taiga-ud-dev.conllu.sh
qsub -cwd -j y -l mem_free=10G,act_mem_free=10G,h_vmem=12G -M droganova@ufal.mff.cuni.cz -m beas gun_thomas-ud-test.conllu.sh
qsub -cwd -j y -l mem_free=10G,act_mem_free=10G,h_vmem=12G -M droganova@ufal.mff.cuni.cz -m beas cs_pud-ud-test.conllu.sh
qsub -cwd -j y -l mem_free=10G,act_mem_free=10G,h_vmem=12G -M droganova@ufal.mff.cuni.cz -m beas fr_ftb-ud-train.conllu.sh
qsub -cwd -j y -l mem_free=10G,act_mem_free=10G,h_vmem=12G -M droganova@ufal.mff.cuni.cz -m beas fr_ftb-ud-dev.conllu.sh
qsub -cwd -j y -l mem_free=10G,act_mem_free=10G,h_vmem=12G -M droganova@ufal.mff.cuni.cz -m beas fr_ftb-ud-test.conllu.sh
qsub -cwd -j y -l mem_free=10G,act_mem_free=10G,h_vmem=12G -M droganova@ufal.mff.cuni.cz -m beas cs_pdt-ud-dev.conllu.sh
qsub -cwd -j y -l mem_free=10G,act_mem_free=10G,h_vmem=12G -M droganova@ufal.mff.cuni.cz -m beas cs_pdt-ud-train.conllu.sh
qsub -cwd -j y -l mem_free=10G,act_mem_free=10G,h_vmem=12G -M droganova@ufal.mff.cuni.cz -m beas cs_pdt-ud-test.conllu.sh
qsub -cwd -j y -l mem_free=10G,act_mem_free=10G,h_vmem=12G -M droganova@ufal.mff.cuni.cz -m beas ru_syntagrus-ud-dev.conllu.sh
qsub -cwd -j y -l mem_free=10G,act_mem_free=10G,h_vmem=12G -M droganova@ufal.mff.cuni.cz -m beas ru_syntagrus-ud-test.conllu.sh
qsub -cwd -j y -l mem_free=10G,act_mem_free=10G,h_vmem=12G -M droganova@ufal.mff.cuni.cz -m beas ru_syntagrus-ud-train.conllu.sh
qsub -cwd -j y -l mem_free=10G,act_mem_free=10G,h_vmem=12G -M droganova@ufal.mff.cuni.cz -m beas fro_srcmf-ud-test.conllu.sh
qsub -cwd -j y -l mem_free=10G,act_mem_free=10G,h_vmem=12G -M droganova@ufal.mff.cuni.cz -m beas fro_srcmf-ud-dev.conllu.sh
qsub -cwd -j y -l mem_free=10G,act_mem_free=10G,h_vmem=12G -M droganova@ufal.mff.cuni.cz -m beas fro_srcmf-ud-train.conllu.sh
qsub -cwd -j y -l mem_free=10G,act_mem_free=10G,h_vmem=12G -M droganova@ufal.mff.cuni.cz -m beas krl_kkpp-ud-test.conllu.sh
qsub -cwd -j y -l mem_free=10G,act_mem_free=10G,h_vmem=12G -M droganova@ufal.mff.cuni.cz -m beas la_perseus-ud-train.conllu.sh
qsub -cwd -j y -l mem_free=10G,act_mem_free=10G,h_vmem=12G -M droganova@ufal.mff.cuni.cz -m beas la_perseus-ud-test.conllu.sh
qsub -cwd -j y -l mem_free=10G,act_mem_free=10G,h_vmem=12G -M droganova@ufal.mff.cuni.cz -m beas ar_padt-ud-test.conllu.sh
qsub -cwd -j y -l mem_free=10G,act_mem_free=10G,h_vmem=12G -M droganova@ufal.mff.cuni.cz -m beas ar_padt-ud-train.conllu.sh
qsub -cwd -j y -l mem_free=10G,act_mem_free=10G,h_vmem=12G -M droganova@ufal.mff.cuni.cz -m beas ar_padt-ud-dev.conllu.sh
qsub -cwd -j y -l mem_free=10G,act_mem_free=10G,h_vmem=12G -M droganova@ufal.mff.cuni.cz -m beas fr_sequoia-ud-test.conllu.sh
qsub -cwd -j y -l mem_free=10G,act_mem_free=10G,h_vmem=12G -M droganova@ufal.mff.cuni.cz -m beas fr_sequoia-ud-train.conllu.sh
qsub -cwd -j y -l mem_free=10G,act_mem_free=10G,h_vmem=12G -M droganova@ufal.mff.cuni.cz -m beas fr_sequoia-ud-dev.conllu.sh
qsub -cwd -j y -l mem_free=10G,act_mem_free=10G,h_vmem=12G -M droganova@ufal.mff.cuni.cz -m beas es_pud-ud-test.conllu.sh
qsub -cwd -j y -l mem_free=10G,act_mem_free=10G,h_vmem=12G -M droganova@ufal.mff.cuni.cz -m beas es_gsd-ud-test.conllu.sh
qsub -cwd -j y -l mem_free=10G,act_mem_free=10G,h_vmem=12G -M droganova@ufal.mff.cuni.cz -m beas es_gsd-ud-train.conllu.sh
qsub -cwd -j y -l mem_free=10G,act_mem_free=10G,h_vmem=12G -M droganova@ufal.mff.cuni.cz -m beas es_gsd-ud-dev.conllu.sh
qsub -cwd -j y -l mem_free=10G,act_mem_free=10G,h_vmem=12G -M droganova@ufal.mff.cuni.cz -m beas he_htb-ud-train.conllu.sh
qsub -cwd -j y -l mem_free=10G,act_mem_free=10G,h_vmem=12G -M droganova@ufal.mff.cuni.cz -m beas he_htb-ud-test.conllu.sh
qsub -cwd -j y -l mem_free=10G,act_mem_free=10G,h_vmem=12G -M droganova@ufal.mff.cuni.cz -m beas he_htb-ud-dev.conllu.sh
qsub -cwd -j y -l mem_free=10G,act_mem_free=10G,h_vmem=12G -M droganova@ufal.mff.cuni.cz -m beas en_lines-ud-dev.conllu.sh
qsub -cwd -j y -l mem_free=10G,act_mem_free=10G,h_vmem=12G -M droganova@ufal.mff.cuni.cz -m beas en_lines-ud-test.conllu.sh
qsub -cwd -j y -l mem_free=10G,act_mem_free=10G,h_vmem=12G -M droganova@ufal.mff.cuni.cz -m beas en_lines-ud-train.conllu.sh
qsub -cwd -j y -l mem_free=10G,act_mem_free=10G,h_vmem=12G -M droganova@ufal.mff.cuni.cz -m beas zh_gsd-ud-dev.conllu.sh
qsub -cwd -j y -l mem_free=10G,act_mem_free=10G,h_vmem=12G -M droganova@ufal.mff.cuni.cz -m beas zh_gsd-ud-test.conllu.sh
qsub -cwd -j y -l mem_free=10G,act_mem_free=10G,h_vmem=12G -M droganova@ufal.mff.cuni.cz -m beas zh_gsd-ud-train.conllu.sh
qsub -cwd -j y -l mem_free=10G,act_mem_free=10G,h_vmem=12G -M droganova@ufal.mff.cuni.cz -m beas zh_pud-ud-test.conllu.sh
qsub -cwd -j y -l mem_free=10G,act_mem_free=10G,h_vmem=12G -M droganova@ufal.mff.cuni.cz -m beas th_pud-ud-test.conllu.sh
qsub -cwd -j y -l mem_free=10G,act_mem_free=10G,h_vmem=12G -M droganova@ufal.mff.cuni.cz -m beas de_hdt-ud-train-b.conllu.sh
qsub -cwd -j y -l mem_free=10G,act_mem_free=10G,h_vmem=12G -M droganova@ufal.mff.cuni.cz -m beas de_hdt-ud-test.conllu.sh
qsub -cwd -j y -l mem_free=10G,act_mem_free=10G,h_vmem=12G -M droganova@ufal.mff.cuni.cz -m beas de_hdt-ud-dev.conllu.sh
qsub -cwd -j y -l mem_free=10G,act_mem_free=10G,h_vmem=12G -M droganova@ufal.mff.cuni.cz -m beas de_hdt-ud-train-a.conllu.sh
qsub -cwd -j y -l mem_free=10G,act_mem_free=10G,h_vmem=12G -M droganova@ufal.mff.cuni.cz -m beas hi_hdtb-ud-train.conllu.sh
qsub -cwd -j y -l mem_free=10G,act_mem_free=10G,h_vmem=12G -M droganova@ufal.mff.cuni.cz -m beas hi_hdtb-ud-test.conllu.sh
qsub -cwd -j y -l mem_free=10G,act_mem_free=10G,h_vmem=12G -M droganova@ufal.mff.cuni.cz -m beas hi_hdtb-ud-dev.conllu.sh
qsub -cwd -j y -l mem_free=10G,act_mem_free=10G,h_vmem=12G -M droganova@ufal.mff.cuni.cz -m beas lt_alksnis-ud-test.conllu.sh
qsub -cwd -j y -l mem_free=10G,act_mem_free=10G,h_vmem=12G -M droganova@ufal.mff.cuni.cz -m beas lt_alksnis-ud-dev.conllu.sh
qsub -cwd -j y -l mem_free=10G,act_mem_free=10G,h_vmem=12G -M droganova@ufal.mff.cuni.cz -m beas lt_alksnis-ud-train.conllu.sh
qsub -cwd -j y -l mem_free=10G,act_mem_free=10G,h_vmem=12G -M droganova@ufal.mff.cuni.cz -m beas ko_pud-ud-test.conllu.sh
qsub -cwd -j y -l mem_free=10G,act_mem_free=10G,h_vmem=12G -M droganova@ufal.mff.cuni.cz -m beas ko_gsd-ud-dev.conllu.sh
qsub -cwd -j y -l mem_free=10G,act_mem_free=10G,h_vmem=12G -M droganova@ufal.mff.cuni.cz -m beas ko_gsd-ud-test.conllu.sh
qsub -cwd -j y -l mem_free=10G,act_mem_free=10G,h_vmem=12G -M droganova@ufal.mff.cuni.cz -m beas ko_gsd-ud-train.conllu.sh
qsub -cwd -j y -l mem_free=10G,act_mem_free=10G,h_vmem=12G -M droganova@ufal.mff.cuni.cz -m beas sa_ufal-ud-test.conllu.sh
qsub -cwd -j y -l mem_free=10G,act_mem_free=10G,h_vmem=12G -M droganova@ufal.mff.cuni.cz -m beas en_partut-ud-train.conllu.sh
qsub -cwd -j y -l mem_free=10G,act_mem_free=10G,h_vmem=12G -M droganova@ufal.mff.cuni.cz -m beas en_partut-ud-dev.conllu.sh
qsub -cwd -j y -l mem_free=10G,act_mem_free=10G,h_vmem=12G -M droganova@ufal.mff.cuni.cz -m beas en_partut-ud-test.conllu.sh
qsub -cwd -j y -l mem_free=10G,act_mem_free=10G,h_vmem=12G -M droganova@ufal.mff.cuni.cz -m beas fi_pud-ud-test.conllu.sh
qsub -cwd -j y -l mem_free=10G,act_mem_free=10G,h_vmem=12G -M droganova@ufal.mff.cuni.cz -m beas ur_udtb-ud-train.conllu.sh
qsub -cwd -j y -l mem_free=10G,act_mem_free=10G,h_vmem=12G -M droganova@ufal.mff.cuni.cz -m beas ur_udtb-ud-dev.conllu.sh
qsub -cwd -j y -l mem_free=10G,act_mem_free=10G,h_vmem=12G -M droganova@ufal.mff.cuni.cz -m beas ur_udtb-ud-test.conllu.sh
qsub -cwd -j y -l mem_free=10G,act_mem_free=10G,h_vmem=12G -M droganova@ufal.mff.cuni.cz -m beas grc_perseus-ud-train.conllu.sh
qsub -cwd -j y -l mem_free=10G,act_mem_free=10G,h_vmem=12G -M droganova@ufal.mff.cuni.cz -m beas grc_perseus-ud-dev.conllu.sh
qsub -cwd -j y -l mem_free=10G,act_mem_free=10G,h_vmem=12G -M droganova@ufal.mff.cuni.cz -m beas grc_perseus-ud-test.conllu.sh
qsub -cwd -j y -l mem_free=10G,act_mem_free=10G,h_vmem=12G -M droganova@ufal.mff.cuni.cz -m beas cop_scriptorium-ud-test.conllu.sh
qsub -cwd -j y -l mem_free=10G,act_mem_free=10G,h_vmem=12G -M droganova@ufal.mff.cuni.cz -m beas cop_scriptorium-ud-dev.conllu.sh
qsub -cwd -j y -l mem_free=10G,act_mem_free=10G,h_vmem=12G -M droganova@ufal.mff.cuni.cz -m beas cop_scriptorium-ud-train.conllu.sh
qsub -cwd -j y -l mem_free=10G,act_mem_free=10G,h_vmem=12G -M droganova@ufal.mff.cuni.cz -m beas pt_gsd-ud-test.conllu.sh
qsub -cwd -j y -l mem_free=10G,act_mem_free=10G,h_vmem=12G -M droganova@ufal.mff.cuni.cz -m beas pt_gsd-ud-dev.conllu.sh
qsub -cwd -j y -l mem_free=10G,act_mem_free=10G,h_vmem=12G -M droganova@ufal.mff.cuni.cz -m beas pt_gsd-ud-train.conllu.sh
qsub -cwd -j y -l mem_free=10G,act_mem_free=10G,h_vmem=12G -M droganova@ufal.mff.cuni.cz -m beas pt_pud-ud-test.conllu.sh
qsub -cwd -j y -l mem_free=10G,act_mem_free=10G,h_vmem=12G -M droganova@ufal.mff.cuni.cz -m beas ru_gsd-ud-test.conllu.sh
qsub -cwd -j y -l mem_free=10G,act_mem_free=10G,h_vmem=12G -M droganova@ufal.mff.cuni.cz -m beas ru_gsd-ud-train.conllu.sh
qsub -cwd -j y -l mem_free=10G,act_mem_free=10G,h_vmem=12G -M droganova@ufal.mff.cuni.cz -m beas ru_gsd-ud-dev.conllu.sh
qsub -cwd -j y -l mem_free=10G,act_mem_free=10G,h_vmem=12G -M droganova@ufal.mff.cuni.cz -m beas ru_pud-ud-test.conllu.sh
qsub -cwd -j y -l mem_free=10G,act_mem_free=10G,h_vmem=12G -M droganova@ufal.mff.cuni.cz -m beas br_keb-ud-test.conllu.sh
qsub -cwd -j y -l mem_free=10G,act_mem_free=10G,h_vmem=12G -M droganova@ufal.mff.cuni.cz -m beas sv_lines-ud-test.conllu.sh
qsub -cwd -j y -l mem_free=10G,act_mem_free=10G,h_vmem=12G -M droganova@ufal.mff.cuni.cz -m beas sv_lines-ud-train.conllu.sh
qsub -cwd -j y -l mem_free=10G,act_mem_free=10G,h_vmem=12G -M droganova@ufal.mff.cuni.cz -m beas sv_lines-ud-dev.conllu.sh
qsub -cwd -j y -l mem_free=10G,act_mem_free=10G,h_vmem=12G -M droganova@ufal.mff.cuni.cz -m beas ar_nyuad-ud-train.conllu.sh
qsub -cwd -j y -l mem_free=10G,act_mem_free=10G,h_vmem=12G -M droganova@ufal.mff.cuni.cz -m beas ar_nyuad-ud-test.conllu.sh
qsub -cwd -j y -l mem_free=10G,act_mem_free=10G,h_vmem=12G -M droganova@ufal.mff.cuni.cz -m beas ar_nyuad-ud-dev.conllu.sh
qsub -cwd -j y -l mem_free=10G,act_mem_free=10G,h_vmem=12G -M droganova@ufal.mff.cuni.cz -m beas pl_pud-ud-test.conllu.sh
qsub -cwd -j y -l mem_free=10G,act_mem_free=10G,h_vmem=12G -M droganova@ufal.mff.cuni.cz -m beas yo_ytb-ud-test.conllu.sh
qsub -cwd -j y -l mem_free=10G,act_mem_free=10G,h_vmem=12G -M droganova@ufal.mff.cuni.cz -m beas ko_kaist-ud-dev.conllu.sh
qsub -cwd -j y -l mem_free=10G,act_mem_free=10G,h_vmem=12G -M droganova@ufal.mff.cuni.cz -m beas ko_kaist-ud-train.conllu.sh
qsub -cwd -j y -l mem_free=10G,act_mem_free=10G,h_vmem=12G -M droganova@ufal.mff.cuni.cz -m beas ko_kaist-ud-test.conllu.sh
qsub -cwd -j y -l mem_free=10G,act_mem_free=10G,h_vmem=12G -M droganova@ufal.mff.cuni.cz -m beas yue_hk-ud-test.conllu.sh
qsub -cwd -j y -l mem_free=10G,act_mem_free=10G,h_vmem=12G -M droganova@ufal.mff.cuni.cz -m beas la_proiel-ud-dev.conllu.sh
qsub -cwd -j y -l mem_free=10G,act_mem_free=10G,h_vmem=12G -M droganova@ufal.mff.cuni.cz -m beas la_proiel-ud-test.conllu.sh
qsub -cwd -j y -l mem_free=10G,act_mem_free=10G,h_vmem=12G -M droganova@ufal.mff.cuni.cz -m beas la_proiel-ud-train.conllu.sh
qsub -cwd -j y -l mem_free=10G,act_mem_free=10G,h_vmem=12G -M droganova@ufal.mff.cuni.cz -m beas pl_pdb-ud-train.conllu.sh
qsub -cwd -j y -l mem_free=10G,act_mem_free=10G,h_vmem=12G -M droganova@ufal.mff.cuni.cz -m beas pl_pdb-ud-dev.conllu.sh
qsub -cwd -j y -l mem_free=10G,act_mem_free=10G,h_vmem=12G -M droganova@ufal.mff.cuni.cz -m beas pl_pdb-ud-test.conllu.sh
qsub -cwd -j y -l mem_free=10G,act_mem_free=10G,h_vmem=12G -M droganova@ufal.mff.cuni.cz -m beas wo_wtb-ud-dev.conllu.sh
qsub -cwd -j y -l mem_free=10G,act_mem_free=10G,h_vmem=12G -M droganova@ufal.mff.cuni.cz -m beas wo_wtb-ud-test.conllu.sh
qsub -cwd -j y -l mem_free=10G,act_mem_free=10G,h_vmem=12G -M droganova@ufal.mff.cuni.cz -m beas wo_wtb-ud-train.conllu.sh
qsub -cwd -j y -l mem_free=10G,act_mem_free=10G,h_vmem=12G -M droganova@ufal.mff.cuni.cz -m beas mr_ufal-ud-test.conllu.sh
qsub -cwd -j y -l mem_free=10G,act_mem_free=10G,h_vmem=12G -M droganova@ufal.mff.cuni.cz -m beas mr_ufal-ud-train.conllu.sh
qsub -cwd -j y -l mem_free=10G,act_mem_free=10G,h_vmem=12G -M droganova@ufal.mff.cuni.cz -m beas mr_ufal-ud-dev.conllu.sh
qsub -cwd -j y -l mem_free=10G,act_mem_free=10G,h_vmem=12G -M droganova@ufal.mff.cuni.cz -m beas ta_ttb-ud-test.conllu.sh
qsub -cwd -j y -l mem_free=10G,act_mem_free=10G,h_vmem=12G -M droganova@ufal.mff.cuni.cz -m beas ta_ttb-ud-train.conllu.sh
qsub -cwd -j y -l mem_free=10G,act_mem_free=10G,h_vmem=12G -M droganova@ufal.mff.cuni.cz -m beas ta_ttb-ud-dev.conllu.sh
qsub -cwd -j y -l mem_free=10G,act_mem_free=10G,h_vmem=12G -M droganova@ufal.mff.cuni.cz -m beas wbp_ufal-ud-test.conllu.sh
qsub -cwd -j y -l mem_free=10G,act_mem_free=10G,h_vmem=12G -M droganova@ufal.mff.cuni.cz -m beas zh_hk-ud-test.conllu.sh
qsub -cwd -j y -l mem_free=10G,act_mem_free=10G,h_vmem=12G -M droganova@ufal.mff.cuni.cz -m beas el_gdt-ud-train.conllu.sh
qsub -cwd -j y -l mem_free=10G,act_mem_free=10G,h_vmem=12G -M droganova@ufal.mff.cuni.cz -m beas el_gdt-ud-dev.conllu.sh
qsub -cwd -j y -l mem_free=10G,act_mem_free=10G,h_vmem=12G -M droganova@ufal.mff.cuni.cz -m beas el_gdt-ud-test.conllu.sh
qsub -cwd -j y -l mem_free=10G,act_mem_free=10G,h_vmem=12G -M droganova@ufal.mff.cuni.cz -m beas grc_proiel-ud-train.conllu.sh
qsub -cwd -j y -l mem_free=10G,act_mem_free=10G,h_vmem=12G -M droganova@ufal.mff.cuni.cz -m beas grc_proiel-ud-test.conllu.sh
qsub -cwd -j y -l mem_free=10G,act_mem_free=10G,h_vmem=12G -M droganova@ufal.mff.cuni.cz -m beas grc_proiel-ud-dev.conllu.sh
qsub -cwd -j y -l mem_free=10G,act_mem_free=10G,h_vmem=12G -M droganova@ufal.mff.cuni.cz -m beas te_mtg-ud-train.conllu.sh
qsub -cwd -j y -l mem_free=10G,act_mem_free=10G,h_vmem=12G -M droganova@ufal.mff.cuni.cz -m beas te_mtg-ud-dev.conllu.sh
qsub -cwd -j y -l mem_free=10G,act_mem_free=10G,h_vmem=12G -M droganova@ufal.mff.cuni.cz -m beas te_mtg-ud-test.conllu.sh
qsub -cwd -j y -l mem_free=10G,act_mem_free=10G,h_vmem=12G -M droganova@ufal.mff.cuni.cz -m beas cs_fictree-ud-dev.conllu.sh
qsub -cwd -j y -l mem_free=10G,act_mem_free=10G,h_vmem=12G -M droganova@ufal.mff.cuni.cz -m beas cs_fictree-ud-train.conllu.sh
qsub -cwd -j y -l mem_free=10G,act_mem_free=10G,h_vmem=12G -M droganova@ufal.mff.cuni.cz -m beas cs_fictree-ud-test.conllu.sh
qsub -cwd -j y -l mem_free=10G,act_mem_free=10G,h_vmem=12G -M droganova@ufal.mff.cuni.cz -m beas en_esl-ud-dev.conllu.sh
qsub -cwd -j y -l mem_free=10G,act_mem_free=10G,h_vmem=12G -M droganova@ufal.mff.cuni.cz -m beas en_esl-ud-train.conllu.sh
qsub -cwd -j y -l mem_free=10G,act_mem_free=10G,h_vmem=12G -M droganova@ufal.mff.cuni.cz -m beas en_esl-ud-test.conllu.sh
qsub -cwd -j y -l mem_free=10G,act_mem_free=10G,h_vmem=12G -M droganova@ufal.mff.cuni.cz -m beas tl_trg-ud-test.conllu.sh
qsub -cwd -j y -l mem_free=10G,act_mem_free=10G,h_vmem=12G -M droganova@ufal.mff.cuni.cz -m beas no_nynorsk-ud-dev.conllu.sh
qsub -cwd -j y -l mem_free=10G,act_mem_free=10G,h_vmem=12G -M droganova@ufal.mff.cuni.cz -m beas no_nynorsk-ud-test.conllu.sh
qsub -cwd -j y -l mem_free=10G,act_mem_free=10G,h_vmem=12G -M droganova@ufal.mff.cuni.cz -m beas no_nynorsk-ud-train.conllu.sh
qsub -cwd -j y -l mem_free=10G,act_mem_free=10G,h_vmem=12G -M droganova@ufal.mff.cuni.cz -m beas lzh_kyoto-ud-test.conllu.sh
qsub -cwd -j y -l mem_free=10G,act_mem_free=10G,h_vmem=12G -M droganova@ufal.mff.cuni.cz -m beas lzh_kyoto-ud-train.conllu.sh
qsub -cwd -j y -l mem_free=10G,act_mem_free=10G,h_vmem=12G -M droganova@ufal.mff.cuni.cz -m beas lzh_kyoto-ud-dev.conllu.sh
qsub -cwd -j y -l mem_free=10G,act_mem_free=10G,h_vmem=12G -M droganova@ufal.mff.cuni.cz -m beas fa_seraji-ud-dev.conllu.sh
qsub -cwd -j y -l mem_free=10G,act_mem_free=10G,h_vmem=12G -M droganova@ufal.mff.cuni.cz -m beas fa_seraji-ud-train.conllu.sh
qsub -cwd -j y -l mem_free=10G,act_mem_free=10G,h_vmem=12G -M droganova@ufal.mff.cuni.cz -m beas fa_seraji-ud-test.conllu.sh
qsub -cwd -j y -l mem_free=10G,act_mem_free=10G,h_vmem=12G -M droganova@ufal.mff.cuni.cz -m beas ro_nonstandard-ud-test.conllu.sh
qsub -cwd -j y -l mem_free=10G,act_mem_free=10G,h_vmem=12G -M droganova@ufal.mff.cuni.cz -m beas ro_nonstandard-ud-dev.conllu.sh
qsub -cwd -j y -l mem_free=10G,act_mem_free=10G,h_vmem=12G -M droganova@ufal.mff.cuni.cz -m beas ro_nonstandard-ud-train.conllu.sh
qsub -cwd -j y -l mem_free=10G,act_mem_free=10G,h_vmem=12G -M droganova@ufal.mff.cuni.cz -m beas fr_partut-ud-train.conllu.sh
qsub -cwd -j y -l mem_free=10G,act_mem_free=10G,h_vmem=12G -M droganova@ufal.mff.cuni.cz -m beas fr_partut-ud-test.conllu.sh
qsub -cwd -j y -l mem_free=10G,act_mem_free=10G,h_vmem=12G -M droganova@ufal.mff.cuni.cz -m beas fr_partut-ud-dev.conllu.sh
qsub -cwd -j y -l mem_free=10G,act_mem_free=10G,h_vmem=12G -M droganova@ufal.mff.cuni.cz -m beas ja_modern-ud-test.conllu.sh
qsub -cwd -j y -l mem_free=10G,act_mem_free=10G,h_vmem=12G -M droganova@ufal.mff.cuni.cz -m beas fi_tdt-ud-dev.conllu.sh
qsub -cwd -j y -l mem_free=10G,act_mem_free=10G,h_vmem=12G -M droganova@ufal.mff.cuni.cz -m beas fi_tdt-ud-train.conllu.sh
qsub -cwd -j y -l mem_free=10G,act_mem_free=10G,h_vmem=12G -M droganova@ufal.mff.cuni.cz -m beas fi_tdt-ud-test.conllu.sh
qsub -cwd -j y -l mem_free=10G,act_mem_free=10G,h_vmem=12G -M droganova@ufal.mff.cuni.cz -m beas pl_lfg-ud-test.conllu.sh
qsub -cwd -j y -l mem_free=10G,act_mem_free=10G,h_vmem=12G -M droganova@ufal.mff.cuni.cz -m beas pl_lfg-ud-dev.conllu.sh
qsub -cwd -j y -l mem_free=10G,act_mem_free=10G,h_vmem=12G -M droganova@ufal.mff.cuni.cz -m beas pl_lfg-ud-train.conllu.sh
qsub -cwd -j y -l mem_free=10G,act_mem_free=10G,h_vmem=12G -M droganova@ufal.mff.cuni.cz -m beas cs_cltt-ud-dev.conllu.sh
qsub -cwd -j y -l mem_free=10G,act_mem_free=10G,h_vmem=12G -M droganova@ufal.mff.cuni.cz -m beas cs_cltt-ud-test.conllu.sh
qsub -cwd -j y -l mem_free=10G,act_mem_free=10G,h_vmem=12G -M droganova@ufal.mff.cuni.cz -m beas cs_cltt-ud-train.conllu.sh
qsub -cwd -j y -l mem_free=10G,act_mem_free=10G,h_vmem=12G -M droganova@ufal.mff.cuni.cz -m beas sv_talbanken-ud-train.conllu.sh
qsub -cwd -j y -l mem_free=10G,act_mem_free=10G,h_vmem=12G -M droganova@ufal.mff.cuni.cz -m beas sv_talbanken-ud-test.conllu.sh
qsub -cwd -j y -l mem_free=10G,act_mem_free=10G,h_vmem=12G -M droganova@ufal.mff.cuni.cz -m beas sv_talbanken-ud-dev.conllu.sh
qsub -cwd -j y -l mem_free=10G,act_mem_free=10G,h_vmem=12G -M droganova@ufal.mff.cuni.cz -m beas lv_lvtb-ud-train.conllu.sh
qsub -cwd -j y -l mem_free=10G,act_mem_free=10G,h_vmem=12G -M droganova@ufal.mff.cuni.cz -m beas lv_lvtb-ud-test.conllu.sh
qsub -cwd -j y -l mem_free=10G,act_mem_free=10G,h_vmem=12G -M droganova@ufal.mff.cuni.cz -m beas lv_lvtb-ud-dev.conllu.sh
qsub -cwd -j y -l mem_free=10G,act_mem_free=10G,h_vmem=12G -M droganova@ufal.mff.cuni.cz -m beas cy_ccg-ud-test.conllu.sh
qsub -cwd -j y -l mem_free=10G,act_mem_free=10G,h_vmem=12G -M droganova@ufal.mff.cuni.cz -m beas it_vit-ud-test.conllu.sh
qsub -cwd -j y -l mem_free=10G,act_mem_free=10G,h_vmem=12G -M droganova@ufal.mff.cuni.cz -m beas it_vit-ud-dev.conllu.sh
qsub -cwd -j y -l mem_free=10G,act_mem_free=10G,h_vmem=12G -M droganova@ufal.mff.cuni.cz -m beas it_vit-ud-train.conllu.sh
qsub -cwd -j y -l mem_free=10G,act_mem_free=10G,h_vmem=12G -M droganova@ufal.mff.cuni.cz -m beas bxr_bdt-ud-train.conllu.sh
qsub -cwd -j y -l mem_free=10G,act_mem_free=10G,h_vmem=12G -M droganova@ufal.mff.cuni.cz -m beas bxr_bdt-ud-test.conllu.sh
qsub -cwd -j y -l mem_free=10G,act_mem_free=10G,h_vmem=12G -M droganova@ufal.mff.cuni.cz -m beas it_pud-ud-test.conllu.sh
qsub -cwd -j y -l mem_free=10G,act_mem_free=10G,h_vmem=12G -M droganova@ufal.mff.cuni.cz -m beas orv_rnc-ud-test.conllu.sh
qsub -cwd -j y -l mem_free=10G,act_mem_free=10G,h_vmem=12G -M droganova@ufal.mff.cuni.cz -m beas no_nynorsklia-ud-test.conllu.sh
qsub -cwd -j y -l mem_free=10G,act_mem_free=10G,h_vmem=12G -M droganova@ufal.mff.cuni.cz -m beas no_nynorsklia-ud-train.conllu.sh
qsub -cwd -j y -l mem_free=10G,act_mem_free=10G,h_vmem=12G -M droganova@ufal.mff.cuni.cz -m beas no_nynorsklia-ud-dev.conllu.sh
qsub -cwd -j y -l mem_free=10G,act_mem_free=10G,h_vmem=12G -M droganova@ufal.mff.cuni.cz -m beas akk_pisandub-ud-test.conllu.sh
qsub -cwd -j y -l mem_free=10G,act_mem_free=10G,h_vmem=12G -M droganova@ufal.mff.cuni.cz -m beas swl_sslc-ud-dev.conllu.sh
qsub -cwd -j y -l mem_free=10G,act_mem_free=10G,h_vmem=12G -M droganova@ufal.mff.cuni.cz -m beas swl_sslc-ud-train.conllu.sh
qsub -cwd -j y -l mem_free=10G,act_mem_free=10G,h_vmem=12G -M droganova@ufal.mff.cuni.cz -m beas swl_sslc-ud-test.conllu.sh
qsub -cwd -j y -l mem_free=10G,act_mem_free=10G,h_vmem=12G -M droganova@ufal.mff.cuni.cz -m beas ja_bccwj-ud-dev.conllu.sh
qsub -cwd -j y -l mem_free=10G,act_mem_free=10G,h_vmem=12G -M droganova@ufal.mff.cuni.cz -m beas ja_bccwj-ud-train.conllu.sh
qsub -cwd -j y -l mem_free=10G,act_mem_free=10G,h_vmem=12G -M droganova@ufal.mff.cuni.cz -m beas ja_bccwj-ud-test.conllu.sh
qsub -cwd -j y -l mem_free=10G,act_mem_free=10G,h_vmem=12G -M droganova@ufal.mff.cuni.cz -m beas hi_pud-ud-test.conllu.sh
qsub -cwd -j y -l mem_free=10G,act_mem_free=10G,h_vmem=12G -M droganova@ufal.mff.cuni.cz -m beas no_bokmaal-ud-dev.conllu.sh
qsub -cwd -j y -l mem_free=10G,act_mem_free=10G,h_vmem=12G -M droganova@ufal.mff.cuni.cz -m beas no_bokmaal-ud-train.conllu.sh
qsub -cwd -j y -l mem_free=10G,act_mem_free=10G,h_vmem=12G -M droganova@ufal.mff.cuni.cz -m beas no_bokmaal-ud-test.conllu.sh
qsub -cwd -j y -l mem_free=10G,act_mem_free=10G,h_vmem=12G -M droganova@ufal.mff.cuni.cz -m beas qhe_hiencs-ud-dev.conllu.sh
qsub -cwd -j y -l mem_free=10G,act_mem_free=10G,h_vmem=12G -M droganova@ufal.mff.cuni.cz -m beas qhe_hiencs-ud-train.conllu.sh
qsub -cwd -j y -l mem_free=10G,act_mem_free=10G,h_vmem=12G -M droganova@ufal.mff.cuni.cz -m beas qhe_hiencs-ud-test.conllu.sh
qsub -cwd -j y -l mem_free=10G,act_mem_free=10G,h_vmem=12G -M droganova@ufal.mff.cuni.cz -m beas hr_set-ud-train.conllu.sh
qsub -cwd -j y -l mem_free=10G,act_mem_free=10G,h_vmem=12G -M droganova@ufal.mff.cuni.cz -m beas hr_set-ud-dev.conllu.sh
qsub -cwd -j y -l mem_free=10G,act_mem_free=10G,h_vmem=12G -M droganova@ufal.mff.cuni.cz -m beas hr_set-ud-test.conllu.sh
qsub -cwd -j y -l mem_free=10G,act_mem_free=10G,h_vmem=12G -M droganova@ufal.mff.cuni.cz -m beas ga_idt-ud-test.conllu.sh
qsub -cwd -j y -l mem_free=10G,act_mem_free=10G,h_vmem=12G -M droganova@ufal.mff.cuni.cz -m beas ga_idt-ud-train.conllu.sh
qsub -cwd -j y -l mem_free=10G,act_mem_free=10G,h_vmem=12G -M droganova@ufal.mff.cuni.cz -m beas fr_gsd-ud-dev.conllu.sh
qsub -cwd -j y -l mem_free=10G,act_mem_free=10G,h_vmem=12G -M droganova@ufal.mff.cuni.cz -m beas fr_gsd-ud-train.conllu.sh
qsub -cwd -j y -l mem_free=10G,act_mem_free=10G,h_vmem=12G -M droganova@ufal.mff.cuni.cz -m beas fr_gsd-ud-test.conllu.sh
qsub -cwd -j y -l mem_free=10G,act_mem_free=10G,h_vmem=12G -M droganova@ufal.mff.cuni.cz -m beas fr_pud-ud-test.conllu.sh
qsub -cwd -j y -l mem_free=10G,act_mem_free=10G,h_vmem=12G -M droganova@ufal.mff.cuni.cz -m beas be_hse-ud-test.conllu.sh
qsub -cwd -j y -l mem_free=10G,act_mem_free=10G,h_vmem=12G -M droganova@ufal.mff.cuni.cz -m beas be_hse-ud-dev.conllu.sh
qsub -cwd -j y -l mem_free=10G,act_mem_free=10G,h_vmem=12G -M droganova@ufal.mff.cuni.cz -m beas be_hse-ud-train.conllu.sh
qsub -cwd -j y -l mem_free=10G,act_mem_free=10G,h_vmem=12G -M droganova@ufal.mff.cuni.cz -m beas nl_alpino-ud-test.conllu.sh
qsub -cwd -j y -l mem_free=10G,act_mem_free=10G,h_vmem=12G -M droganova@ufal.mff.cuni.cz -m beas nl_alpino-ud-dev.conllu.sh
qsub -cwd -j y -l mem_free=10G,act_mem_free=10G,h_vmem=12G -M droganova@ufal.mff.cuni.cz -m beas nl_alpino-ud-train.conllu.sh
qsub -cwd -j y -l mem_free=10G,act_mem_free=10G,h_vmem=12G -M droganova@ufal.mff.cuni.cz -m beas kpv_lattice-ud-test.conllu.sh
qsub -cwd -j y -l mem_free=10G,act_mem_free=10G,h_vmem=12G -M droganova@ufal.mff.cuni.cz -m beas sv_pud-ud-test.conllu.sh
qsub -cwd -j y -l mem_free=10G,act_mem_free=10G,h_vmem=12G -M droganova@ufal.mff.cuni.cz -m beas pcm_nsc-ud-test.conllu.sh
qsub -cwd -j y -l mem_free=10G,act_mem_free=10G,h_vmem=12G -M droganova@ufal.mff.cuni.cz -m beas sl_ssj-ud-train.conllu.sh
qsub -cwd -j y -l mem_free=10G,act_mem_free=10G,h_vmem=12G -M droganova@ufal.mff.cuni.cz -m beas sl_ssj-ud-dev.conllu.sh
qsub -cwd -j y -l mem_free=10G,act_mem_free=10G,h_vmem=12G -M droganova@ufal.mff.cuni.cz -m beas sl_ssj-ud-test.conllu.sh
qsub -cwd -j y -l mem_free=10G,act_mem_free=10G,h_vmem=12G -M droganova@ufal.mff.cuni.cz -m beas bm_crb-ud-test.conllu.sh
qsub -cwd -j y -l mem_free=10G,act_mem_free=10G,h_vmem=12G -M droganova@ufal.mff.cuni.cz -m beas sme_giella-ud-train.conllu.sh
qsub -cwd -j y -l mem_free=10G,act_mem_free=10G,h_vmem=12G -M droganova@ufal.mff.cuni.cz -m beas sme_giella-ud-test.conllu.sh
qsub -cwd -j y -l mem_free=10G,act_mem_free=10G,h_vmem=12G -M droganova@ufal.mff.cuni.cz -m beas fo_oft-ud-test.conllu.sh
qsub -cwd -j y -l mem_free=10G,act_mem_free=10G,h_vmem=12G -M droganova@ufal.mff.cuni.cz -m beas sl_sst-ud-test.conllu.sh
qsub -cwd -j y -l mem_free=10G,act_mem_free=10G,h_vmem=12G -M droganova@ufal.mff.cuni.cz -m beas sl_sst-ud-train.conllu.sh
qsub -cwd -j y -l mem_free=10G,act_mem_free=10G,h_vmem=12G -M droganova@ufal.mff.cuni.cz -m beas de_gsd-ud-train.conllu.sh
qsub -cwd -j y -l mem_free=10G,act_mem_free=10G,h_vmem=12G -M droganova@ufal.mff.cuni.cz -m beas de_gsd-ud-test.conllu.sh
qsub -cwd -j y -l mem_free=10G,act_mem_free=10G,h_vmem=12G -M droganova@ufal.mff.cuni.cz -m beas de_gsd-ud-dev.conllu.sh
qsub -cwd -j y -l mem_free=10G,act_mem_free=10G,h_vmem=12G -M droganova@ufal.mff.cuni.cz -m beas de_pud-ud-test.conllu.sh
qsub -cwd -j y -l mem_free=10G,act_mem_free=10G,h_vmem=12G -M droganova@ufal.mff.cuni.cz -m beas vi_vtb-ud-train.conllu.sh
qsub -cwd -j y -l mem_free=10G,act_mem_free=10G,h_vmem=12G -M droganova@ufal.mff.cuni.cz -m beas vi_vtb-ud-dev.conllu.sh
qsub -cwd -j y -l mem_free=10G,act_mem_free=10G,h_vmem=12G -M droganova@ufal.mff.cuni.cz -m beas vi_vtb-ud-test.conllu.sh
qsub -cwd -j y -l mem_free=10G,act_mem_free=10G,h_vmem=12G -M droganova@ufal.mff.cuni.cz -m beas fr_spoken-ud-train.conllu.sh
qsub -cwd -j y -l mem_free=10G,act_mem_free=10G,h_vmem=12G -M droganova@ufal.mff.cuni.cz -m beas fr_spoken-ud-dev.conllu.sh
qsub -cwd -j y -l mem_free=10G,act_mem_free=10G,h_vmem=12G -M droganova@ufal.mff.cuni.cz -m beas fr_spoken-ud-test.conllu.sh
qsub -cwd -j y -l mem_free=10G,act_mem_free=10G,h_vmem=12G -M droganova@ufal.mff.cuni.cz -m beas ro_rrt-ud-test.conllu.sh
qsub -cwd -j y -l mem_free=10G,act_mem_free=10G,h_vmem=12G -M droganova@ufal.mff.cuni.cz -m beas ro_rrt-ud-train.conllu.sh
qsub -cwd -j y -l mem_free=10G,act_mem_free=10G,h_vmem=12G -M droganova@ufal.mff.cuni.cz -m beas ro_rrt-ud-dev.conllu.sh
qsub -cwd -j y -l mem_free=10G,act_mem_free=10G,h_vmem=12G -M droganova@ufal.mff.cuni.cz -m beas tr_pud-ud-test.conllu.sh
qsub -cwd -j y -l mem_free=10G,act_mem_free=10G,h_vmem=12G -M droganova@ufal.mff.cuni.cz -m beas fr_fqb-ud-test.conllu.sh
qsub -cwd -j y -l mem_free=10G,act_mem_free=10G,h_vmem=12G -M droganova@ufal.mff.cuni.cz -m beas en_ewt-ud-train.conllu.sh
qsub -cwd -j y -l mem_free=10G,act_mem_free=10G,h_vmem=12G -M droganova@ufal.mff.cuni.cz -m beas en_ewt-ud-test.conllu.sh
qsub -cwd -j y -l mem_free=10G,act_mem_free=10G,h_vmem=12G -M droganova@ufal.mff.cuni.cz -m beas en_ewt-ud-dev.conllu.sh
qsub -cwd -j y -l mem_free=10G,act_mem_free=10G,h_vmem=12G -M droganova@ufal.mff.cuni.cz -m beas am_att-ud-test.conllu.sh
qsub -cwd -j y -l mem_free=10G,act_mem_free=10G,h_vmem=12G -M droganova@ufal.mff.cuni.cz -m beas gl_ctg-ud-train.conllu.sh
qsub -cwd -j y -l mem_free=10G,act_mem_free=10G,h_vmem=12G -M droganova@ufal.mff.cuni.cz -m beas gl_ctg-ud-test.conllu.sh
qsub -cwd -j y -l mem_free=10G,act_mem_free=10G,h_vmem=12G -M droganova@ufal.mff.cuni.cz -m beas gl_ctg-ud-dev.conllu.sh
qsub -cwd -j y -l mem_free=10G,act_mem_free=10G,h_vmem=12G -M droganova@ufal.mff.cuni.cz -m beas zh_cfl-ud-test.conllu.sh
qsub -cwd -j y -l mem_free=10G,act_mem_free=10G,h_vmem=12G -M droganova@ufal.mff.cuni.cz -m beas et_ewt-ud-train.conllu.sh
qsub -cwd -j y -l mem_free=10G,act_mem_free=10G,h_vmem=12G -M droganova@ufal.mff.cuni.cz -m beas et_ewt-ud-test.conllu.sh
qsub -cwd -j y -l mem_free=10G,act_mem_free=10G,h_vmem=12G -M droganova@ufal.mff.cuni.cz -m beas id_pud-ud-test.conllu.sh
qsub -cwd -j y -l mem_free=10G,act_mem_free=10G,h_vmem=12G -M droganova@ufal.mff.cuni.cz -m beas id_gsd-ud-test.conllu.sh
qsub -cwd -j y -l mem_free=10G,act_mem_free=10G,h_vmem=12G -M droganova@ufal.mff.cuni.cz -m beas id_gsd-ud-train.conllu.sh
qsub -cwd -j y -l mem_free=10G,act_mem_free=10G,h_vmem=12G -M droganova@ufal.mff.cuni.cz -m beas id_gsd-ud-dev.conllu.sh
qsub -cwd -j y -l mem_free=10G,act_mem_free=10G,h_vmem=12G -M droganova@ufal.mff.cuni.cz -m beas fi_ftb-ud-train.conllu.sh
qsub -cwd -j y -l mem_free=10G,act_mem_free=10G,h_vmem=12G -M droganova@ufal.mff.cuni.cz -m beas fi_ftb-ud-dev.conllu.sh
qsub -cwd -j y -l mem_free=10G,act_mem_free=10G,h_vmem=12G -M droganova@ufal.mff.cuni.cz -m beas fi_ftb-ud-test.conllu.sh
qsub -cwd -j y -l mem_free=10G,act_mem_free=10G,h_vmem=12G -M droganova@ufal.mff.cuni.cz -m beas gl_treegal-ud-test.conllu.sh
qsub -cwd -j y -l mem_free=10G,act_mem_free=10G,h_vmem=12G -M droganova@ufal.mff.cuni.cz -m beas gl_treegal-ud-train.conllu.sh
qsub -cwd -j y -l mem_free=10G,act_mem_free=10G,h_vmem=12G -M droganova@ufal.mff.cuni.cz -m beas it_postwita-ud-train.conllu.sh
qsub -cwd -j y -l mem_free=10G,act_mem_free=10G,h_vmem=12G -M droganova@ufal.mff.cuni.cz -m beas it_postwita-ud-test.conllu.sh
qsub -cwd -j y -l mem_free=10G,act_mem_free=10G,h_vmem=12G -M droganova@ufal.mff.cuni.cz -m beas it_postwita-ud-dev.conllu.sh
qsub -cwd -j y -l mem_free=10G,act_mem_free=10G,h_vmem=12G -M droganova@ufal.mff.cuni.cz -m beas lt_hse-ud-dev.conllu.sh
qsub -cwd -j y -l mem_free=10G,act_mem_free=10G,h_vmem=12G -M droganova@ufal.mff.cuni.cz -m beas lt_hse-ud-test.conllu.sh
qsub -cwd -j y -l mem_free=10G,act_mem_free=10G,h_vmem=12G -M droganova@ufal.mff.cuni.cz -m beas lt_hse-ud-train.conllu.sh
qsub -cwd -j y -l mem_free=10G,act_mem_free=10G,h_vmem=12G -M droganova@ufal.mff.cuni.cz -m beas gun_dooley-ud-test.conllu.sh
qsub -cwd -j y -l mem_free=10G,act_mem_free=10G,h_vmem=12G -M droganova@ufal.mff.cuni.cz -m beas mt_mudt-ud-train.conllu.sh
qsub -cwd -j y -l mem_free=10G,act_mem_free=10G,h_vmem=12G -M droganova@ufal.mff.cuni.cz -m beas mt_mudt-ud-dev.conllu.sh
qsub -cwd -j y -l mem_free=10G,act_mem_free=10G,h_vmem=12G -M droganova@ufal.mff.cuni.cz -m beas mt_mudt-ud-test.conllu.sh
qsub -cwd -j y -l mem_free=10G,act_mem_free=10G,h_vmem=12G -M droganova@ufal.mff.cuni.cz -m beas ar_pud-ud-test.conllu.sh
qsub -cwd -j y -l mem_free=10G,act_mem_free=10G,h_vmem=12G -M droganova@ufal.mff.cuni.cz -m beas myv_jr-ud-test.conllu.sh
qsub -cwd -j y -l mem_free=10G,act_mem_free=10G,h_vmem=12G -M droganova@ufal.mff.cuni.cz -m beas la_ittb-ud-dev.conllu.sh
qsub -cwd -j y -l mem_free=10G,act_mem_free=10G,h_vmem=12G -M droganova@ufal.mff.cuni.cz -m beas la_ittb-ud-train.conllu.sh
qsub -cwd -j y -l mem_free=10G,act_mem_free=10G,h_vmem=12G -M droganova@ufal.mff.cuni.cz -m beas la_ittb-ud-test.conllu.sh
qsub -cwd -j y -l mem_free=10G,act_mem_free=10G,h_vmem=12G -M droganova@ufal.mff.cuni.cz -m beas kmr_mg-ud-train.conllu.sh
qsub -cwd -j y -l mem_free=10G,act_mem_free=10G,h_vmem=12G -M droganova@ufal.mff.cuni.cz -m beas kmr_mg-ud-test.conllu.sh
